apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app_name }}-svc"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- template "labels" . }}
spec:
  selector:
  {{- include "labels" . | indent 2}}
  ports:
  - port: {{ .Values.ingress_port }}
    targetPort: {{ .Values.application_port }}
    appProtocol: tcp
    protocol: TCP 